import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar/Navbar'

const roboto = Roboto({
  weight: [ '300'],
  style: [ 'italic'],
  subsets: ['greek'],
  display: 'auto',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// bg-gradient-to-r from-gray-700 via-gray-900 to-black
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <div className="max-w-auto   mx-auto px-4  sm:px-6 lg-px-8 text-black">
          <div className=' bg-white text-black m-auto p-auto '><Navbar/></div>
        <div>{children}</div>
        </div>
        </body>
    </html>
  )
}
